[package]
name = "map-repeat-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@dharitri.com>"]
edition = "2021"
publish = false

[dependencies.map-repeat]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.2.0"
path = "../../../../../framework/meta"
