[package]
name = "local-dct-and-nft-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.local-dct-and-nft]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.2.0"
path = "../../../../../framework/meta"
